apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: jenkins
data:
  jenkins.yaml: |
    jenkins:
      systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
      numExecutors: 2
      mode: NORMAL
      scmCheckoutRetryCount: 3
      labelString: "master"
      
    security:
      globalJobDslSecurityConfiguration:
        useScriptSecurity: false
        
    unclassified:
      location:
        adminAddress: "admin@example.com"
        url: "http://jenkins.example.com:8080/"
        
    tool:
      git:
        installations:
        - name: "Default"
          home: "git"
      dockerTool:
        installations:
        - name: "Docker"
          home: "/usr/bin/docker"
