apiVersion: v1
kind: Secret
metadata:
  name: jenkins-aws-credentials
  namespace: jenkins
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id = YOUR_ACTUAL_ACCESS_KEY
    aws_secret_access_key = YOUR_ACTUAL_SECRET_KEY
